### PR TITLE
refactor: make sure Brew only has a single constructor

### LINKED ISSUE #9: Unable to distill / barrel-age brews...
So, I was very happy when I saw this brewery fork that constantly updates with a new features, unlike the original plugin. However, I've been strugling trying to make it run properly.

I've been testing some brews when I noticed that plugin is unable to distill brews or age them in barrels. When distillation row ends, instead of giving a completed brew it simply starts again, sending an error to console. In case of aging, after 1 barrel year passes the barrel simply refuses to open, also giving a console error in process. I have no issues brewing anything that doesn't require distillating or aging (e.g. vanilla-config potato soup).

- Also, for some reason every time I put a brew into a brewing stand or barrel, plugin spams messages to console about checking the liquid types of every existing drink, or something like that. Don't know if these 2 issues are connected to each other.

Both the messages spam and the error are provided below:
CunoooNI3PdF3pzjCK802nxOrQbcH2FFogqXSWfjSWE1PzNSMy3IGTcXK42QdHkqngQdAkpBJI4Yc5gOk1T1Vj9h
I have little to no knowledge in Java, so this error doesn't make any sense to me.
If needed, I can provide the error in a text format.

What I have already tried, and it didn't help:
Changing server Java version (tried 17, 18 and 19),
Changing server cores (tried Paper, Pufferfish, PurPur. All on 1.18.2),
Using different fork versions (1.3.0 and 1.2.1),
Using fork together with the original plugin,
Disabling all other plugins,
Deleting all the files and testing it on a clean server,
Clearing worlddata.yml, data.yml and config.yml that were left from the original brewery.

### PR DESCRIPTION
**Pull request by sowelipililimute**
This makes it much easier to uphold invariants, such as liquidType not being null.

Fixes #9.

### CODE REVIEW

**Comment by sowelipililimute** [comment]
@Vutka1 can you verify that this PR fixes the issue for you? You can obtain a .jar of the changes here: https://github.com/BlueMoonVineyard/BreweryNG/actions/runs/4227178086

**Comment by Vutka1** [comment]
@pontaoski , works fine now, thanks =)

**Comment by Vutka1** [comment]
**UPD** @pontaoski uhhhh actually not quite fine. Sometimes I still get an error. I'll reply in #9 a bit later, when I get more information.

**Comment by sowelipililimute** [comment]
that seems like another issue; brewing correctly works fine from what i can tell. merging this since it's an improvement anyhow.

**Pull request merged**
